---

replicaCount: 1

app:
  env:
    API_ROOT_PATH: "/city-search"
    ES_URL: https://prod-xbus.es.europe-west3.gcp.cloud.es.io
  secretEnv:
    SECRET_KEY: ref+vault://gitlab/${CI_PROJECT_PATH}/${CI_ENVIRONMENT_NAME}#/SECRET_KEY
    DB_URL: ref+vault://gitlab/${CI_PROJECT_PATH}/${CI_ENVIRONMENT_NAME}#/DB_URL
    GS_ACCOUNT_KEY: ref+vault://gitlab/${CI_PROJECT_PATH}/${CI_ENVIRONMENT_NAME}#/GS_ACCOUNT_KEY
    ES_API_KEY: ref+vault://gitlab/${CI_PROJECT_PATH}/${CI_ENVIRONMENT_NAME}#/ES_API_KEY

ingress:
  enabled: true
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Access-Control-Allow-Origin: *";
  ingressClassName: nginx
  hosts:
    # The same must be specified in .gitlab-ci.yml as dev url
    - host: svc.playground.internal.distribusion.com
      paths:
        - path: "/city-search(/|$)(.*)"
          type: Prefix

livenessProbe:
  httpGet:
    path: /health
    port: http

readinessProbe:
  httpGet:
    path: /health
    port: http

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 512Mi
