repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: check-yaml
    exclude: ^\.deploy/helm/app/templates/.*\.(yml|yaml)
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    language_version: python3.9
- repo: https://gitlab.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    name: isort (python)
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.960
  hooks:
  - id: mypy
    args: [--no-strict-optional, --ignore-missing-imports]
- repo: https://github.com/pycqa/pylint
  rev: v2.14.0
  hooks:
  - id: pylint
