version: '2'

services:

  postgresql:
    restart: on-failure
    image: postgres:14.2
    container_name: postgresql_cdm
    command:
      - "postgres"
      - "-c"
      - "max_wal_size=5GB"
    env_file: .env
    volumes:
      - db-city-search:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  app:
    image: local/distribusion/city-search:latest
    container_name: app_cdm
    build:
      context: .
      dockerfile: .deploy/docker/Dockerfile
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./:/app
    depends_on:
      - postgresql

volumes:
  db-city-search:
